config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about"
  
  resources :books, only: [:edit, :create, :index, :show, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only:[:index, :show, :edit, :update] do
    get :following
    get :followed
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title, presence: true
	 validates :body,  presence: true, length: { maximum: 200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: 
end

app/models/favorite.rb
class Favorite < ApplicationRecord

   belongs_to :user
   belongs_to :book
   validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy  
  
  validates :name, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def new_kara
    @book_new = Book.new
  end

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  	devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  	#devise_parameter_sanitizer.permit(:account_update, keys: [:name, :introduction, :profile_image])
  end

  def after_sign_up_path_for(resource)
  #   super(resource)
  	user_path(resource)
  end

  # The path used after sign up.
  def after_sign_in_path_for(resource)
  #   super(resource)
  # mypage_path(resource)
  	user_path(resource)
  end

  #passwordなしでupdate
  def update_resource(resource, params)
  	resource.update_without_password(params)
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  before_action :authenticate_user!

    def create
        book = Book.find(params[:book_id]) #コメントする投稿id
        comment = current_user.book_comments.new(book_comment_params)
        comment.book_id = book.id #どの投稿にコメントするか
        comment.save
        redirect_to request.referer
    end

    def destroy
        BookComment.find(params[:id]).destroy
        redirect_to book_path(params[:book_id])
    end

    private

    def book_comment_params
        params.require(:book_comment).permit(:comment)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_action :authenticate_user!
  before_action :find_by?, only:[:show, :edit, :update, :destroy]
  before_action :new_kara, only:[:show, :index]
  before_action :correct_user?, only: [:edit, :update]

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def create
    @book_new = Book.new(book_params)
    if @book_new.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book_new.id)
    else
      @books = Book.all
      render :index
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end


private

  def find_by?
    @book = Book.find(params[:id])
  end

  def correct_user?
    book = Book.find(params[:id])
    if current_user.id != book.user_id
      redirect_to books_path
    end
  end

  def book_params
    params.require(:book).permit(:title, :body, :user_id).merge(:user_id => current_user.id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
  def about
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :user_find_by?, only: [:show, :edit, :update]
	before_action :authenticate_user!
  before_action :new_kara, only: [:show, :index]
  before_action :user_check, only: [:edit, :update]
  
  def show
    @books = Book.where(user_id: @user.id)
  end
  
  def edit
  end
  
  def index
    @users = User.all
  end
  
  def update
    if @user.update(user_params)
      flash[:notice] = "successfully"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end


  private
  
  def user_check
    user = User.find(params[:id])
    if current_user.id != user.id
      redirect_to user_path(current_user.id)
    end
  end
  
  def user_find_by?
  	@user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:profile_image, :name, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment_form.html.erb
<!--コメント入力フォームの部分テンプレート-->

<%= form_with(model:[book, comment], id: "new_comment") do |f| %> <!--配列でインスタンス変数を2つ指定。コメントは、@bookに結びついた@commentだから-->
  <%= f.text_area :comment, rows: '5', class: "textbox", placeholder: "コメントをここに" %> <!--rowはtext_areaの高さ、初期値は2-->
  <%= f.submit "送信する", class: "form_submit, btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

app/views/book_comments/_comment_index.html.erb
<!--コメント一覧の部分テンプレート-->

<% book.book_comments.each do |book_comment| %>
  <tr>
    <td><%= attachment_image_tag book_comment.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %></td>
    <td><%= book_comment.user.name %></td>
    <td><%= book_comment.comment %></td>
    <td><% if user_signed_in? && current_user.id == book_comment.user_id %>
          <%= link_to "Destroy", book_book_comment_path(book, book_comment), method: :delete, data: {confirm: "本当に消しますか？"}, class: "btn btn-danger btn-sm", remote: true %>
        <% end %>
    </td>
  </tr>
<% end %>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3" >
		<h1>Editing Book</h1>
		<%= form_for @book do |f| %>
		<%= render 'layouts/error_messages', model: f.object %>
			<div class="field row">
				<%= f.label :Title %>
				<%= f.text_field :title, class: "col-xs-12" %>
			</div>

			<div class="field row">
				<%= f.label :Opinion %>
				<%= f.text_area :body, class: "col-xs-12" %>
			</div>

			<div class="field row">
				<%= f.submit "Update Book", class: "btn btn-info col-xs-12" %>
			</div>

		<% end %>
		<%= link_to "Show", book_path(@book) %>|
		<%= link_to "Back", books_path %>
	</div>
</div>

app/views/books/index.html.erb
<% if@book_new.errors.any? %>
<%= @book_new.errors.count %>件のエラーが発生しました
          <div class="alert alert-warning">
            <ul>
              <% @book_new.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>



<div class="container px-5 px-sm-0">
	<div class="row">
		<div class="col-md-3">
		<%= render "layouts/lists", user: current_user, book: @book_new %>
		</div>

		<div class="col-md-8 offset-md-1">
		<h2>Books</h2>
			         <table class = "table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
				</thead>
			<tbody>
			<% @books.each do |book| %>
					<tr>
						<td><%= link_to user_path(book.user_id) do %>
						            	<%= image_tag book.user.get_profile_image(100,100) %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book.id) %></td>
					  	<td><%= book.body %></td>
						<td>
							<% if book.favorited_by?(current_user) %>
      				<%= link_to book_favorites_path(book_id: book.id), method: :delete do %>
      				<i class = "fa fa-heart unlike-btn"></i>
        		     	<%= book.favorites.count %>
      				<% end %>
    					  <% else %>
      				<%= link_to book_favorites_path(book_id: book.id), method: :post do %>
      				<i class = "fa fa-heart like-btn"></i>
        			<%= book.favorites.count %>
      				  <% end %>
  		<% end %>
  					</td>
				     <td><%= link_to "コメント数：#{book.book_comments.count}", book_path(book.id) %></td>
					</tr>
			<% end %>
			</tbody>
		</table>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
	<div class="row">
		<div class="col-md-3">
		<%= render "layouts/lists", user: @book.user, book: @book_new	 %>
		</div>

		<div class="col-md-8 offset-md-1">
		<h2>Book detail</h2>
		<table class = "table">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<!-- <th colspan="3"></th> -->
				</tr>
			</thead>

		<tbody>
			<td><%= image_tag @book.user.get_profile_image(100,100) %></td>
			<td><%= @book.title %></td>
			<td><%= @book.body %></td>
			<td><%= render 'favorites/favorite', book: @book %></td>
			<td>コメント数：<%= @book.book_comments.count %></td>
			<% if current_user.id == @book.user_id %>
					<td>
						<%= link_to current_user.name, user_path(current_user) %>
					</td>
					<td>
						<%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success" %>
					</td>
					<td>
						<%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-info", data: { confirm: 'Are you sure?' } %>
					</td>
			<% else %>
					<td>
						<%= link_to @book.user.name, user_path(@book.user_id) %>
					</td>
			<% end %>
		</tbody>
		</table>

				<tr>
  					<% @book.book_comments.each do |book_comment| %>
    				<p>
    				<%= image_tag book_comment.user.get_profile_image(50,50) %>
    				<%= book_comment.comment %>
    				<% if book_comment.user == current_user %>
      				<%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-info" %>
      			<% else %>
      			<% end %>
      				</p>
      				<%= link_to book_comment.user.name, user_path(@book.user_id) %><!-- 名前のリンク先が自分のとこに飛ばない -->
    				<% end %>
				</tr>

					<div>
  				<%= form_with model:[@book, @book_comment] do |f| %>
   				<%= f.text_area :comment, rows:'5' %>
    			<%= f.submit "送信" %>
  				<% end %>
  				</div>
		</div>
	</div>
</div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete do %>
<i class="fa fa-heart unlike-btn"></i>
<%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post do %>
<i class="fa fa-heart like-btn"></i>
<%= book.favorites.count %>
  <% end %>
<% end %>

app/views/homes/about.html.erb
<h1>Welcome to <i class="fas fa-book"></i><strong>Bookers!</strong></h1>

app/views/homes/top.html.erb
<div class="row">
	<div class="top-message col-md-6 col-md-offset-3">
	<h1>Welcome to <i class="fas fa-book" aria-hidden="true"></i>Bookers !!</h1>
	<p>In <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers!</strong>,</p>
	<p>you can share and exchange your opinions ,inpressions , and emotions</p>
	<p>about various books!</p>
	    <div class="btn-wrapper">
			<div class="row">
				<p><%= link_to "Log in", new_user_session_path, class: "col-xs-10 col-xs-offset-1 btn btn-info" %></p>
			</div>
			<div class="row">
				<p><%= link_to "Sign up", new_user_registration_path, class: "col-xs-10 col-xs-offset-1 btn btn-success" %></p>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
      <% logger.debug("-----------errors=#{message}") %>
      <h2>error</h2>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_lists.html.erb
<h2>User info</h2>

<%= image_tag user.get_profile_image(100,100) %>
<table class="table">
	<tbody><tr></tr>
		<tr>
			<th> name </th>
			<th><%= user.name %></th>
		</tr>
		<tr>
			<th> introduction </th>
			<th><%= user.introduction %></th>
			<th></th>
		</tr>
	</tbody>
</table>

<div class="row">
	<%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
	<i class="fas fa-user-cog"></i>
	<% end %>
</div>

<h2 class="mt-3">New book</h2>
<%= form_for book do |f| %>
	<div class="field group">
		<label for="book_opinion"><%= f.label :title %></label>
		<%= f.text_field :title, class: "col-xs-12"%>
	</div>

	<div class="field group">
		<label for="book_opinion"><%= f.label :opinion %></label>
		<%= f.text_area :body, class: "col-xs-12" %>
	</div>

	<div class="field group">
		<%= f.submit "Create Book", class: "btn btn-info col-xs-12" %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/c5784cb359.js" crossorigin="anonymous"></script>!
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", root_path, class: "navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
              <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: "nav-link text-light" do %>
              <i class="fas fa-users"></i> Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path, class: "nav-link text-light" do %>
              <i class="fas fa-book-open"></i> Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
              <i class="fas fa-sign-out-alt"></i> logout
              <% end %>
            </li>
            
            <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: "nav-link text-light" do %>
              <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to home_about_path, class: "nav-link text-light" do %>
              <i class="fas fa-link"></i> About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
              <i class="fas fa-user-plus"></i> sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: "nav-link text-light" do %>
              <i class="fas fa-sign-in-alt"></i> login
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
          </div>
        </nav>
    </header>


    <div class="body">
      <div class="container">
        <% if notice %>
          <p class= "alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class= "alert alert-danger"><%= alert %></p>
        <% end %>
       <%= yield %>
      </div>
    </div>


    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for (@user) do |f| %>
  <%= render "layouts/error_messages", {model: f.object} %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

    <div class="field">
    <%= f.label :profile_image_id %><br />
    <%= f.file_field :profile_image %>
  </div>

    <div class="field">
    <%= f.label :introduction %><br />
    <%= f.text_area :introduction %>
  </div>

  <div class="actions">
    <%= f.submit "Update User" %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
	<div class="row">
		<div class="col-md-3">
		<%= render "layouts/lists", user: current_user, book: @book_new %>
		</div>
		
	<div class="col-md-8 offset-md-1">
		<h2>Users</h2>
		<table class = "table">
			<thead>
				<tr>
					<th></th>
					<th>Name</th>
					<th></th>
					<!-- <th colspan="3"></th> -->
				</tr>
			</thead>
			<tbody>
			<% @users.each do |user| %>
				<tr>
					<td>
						<%= image_tag user.get_profile_image(100,100) %>
					</td>
					<td><%= user.name %></td>
					<td><%= link_to "Show", user_path(user.id) %></td>
				</tr>
			<% end %>
			</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-md-3">
	<%= render "layouts/lists", user: @user, book: @book_new %>
	</div>
	
	<div class="col-md-8 offset-md-1">
		<h2>Books</h2>
		<table class = "table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>
			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td><%= link_to user_path do %>
						<%= image_tag @user.get_profile_image(100, 100) %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book.id) %></td>
					<td><%= book.body %></td>
					<td>
						<% if book.favorited_by?(current_user) %>
      			<%= link_to book_favorites_path(book), method: :delete do %>
      			<i class = "fas fa-heart unlike-btn"></i>
        		<%= book.favorites.count %>
      			<% end %>
    				<% else %>
      			<%= link_to book_favorites_path(book), method: :post do %>
      			<i class = "fas fa-heart like-btn"></i>
        		<%= book.favorites.count %>
      			<% end %>
  					<% end %>
  				</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>